SELECT 
    EXTRACT(MONTH FROM o.ORDERDATE) as MONTH,
    SUM(oi.SALES) as TOTAL_SALES
FROM Orders o
    JOIN Order_Items oi ON o.ORDERNUMBER = oi.ORDERNUMBER
WHERE EXTRACT(YEAR FROM o.ORDERDATE) = 2003
GROUP BY EXTRACT(MONTH FROM o.ORDERDATE)
ORDER BY MONTH;