SELECT 
    c.CUSTOMERNAME, 
    SUM(oi.SALES) as TOTAL_SALES
FROM Customers c 
    JOIN Orders o ON c.ID = o.CUSTOMER_ID
    JOIN Order_Items oi ON o.ORDERNUMBER = oi.ORDERNUMBER
GROUP BY c.CUSTOMERNAME
ORDER BY TOTAL_SALES DESC;